### ISSUE TITLE
Push not delivered to one user when another user push fails.

### ISSUE THREAD

**Issue by s2young** [Orion98MC/node_apns#2]
I am running into an issue when trying to push a message to multiple recipients. In my test, I have two recipients.  One has a bad push token. When attempting the push to the bad token, I properly get an error.  However, subsequent mesages aren't getting delivered.  Even though I am getting sent events from apns.

I am actually trying to test a high volume scenario, so I am sending multiple messages to each of the two users.  When pushing only to the good user, he gets all the messages.  When I add the bad user to the mix, the good user only receives those messages sent BEFORE the first attempt to send to the bad user.

I hope this makes sense.  Any ideas would be much appreciated.  Thanks

**Comment by Orion98MC** [comment]
The bad news:
There is a known issue when dealing with Apple's push service. The feedback is lousy. Also note that the 'sent' event is triggered when a write has been done to the stream's buffer, thus, there is no guaranty that the written bytes are transferred to Apple (see: https://github.com/Orion98MC/node_apns/blob/master/lib/apns.js#L292 ) and on top of this, if the bytes are delivered to Apple, there is still one uncertainty since Apple processes notifications asynchronously and gives no feedback for valid payloads.

The not so bad news:
I managed to implement a 'Almost reliable workflow' to deal with this kind of annoyance. It's a user-land kind of keeping track of sent notifications and waiting a bit for feedback (if ever) to mark them as sent. It may not be the best but I explained it in this article on my blog: http://orion98mc.blogspot.com/2012/12/push-notifications-to-apple-made-almost.html

Anyways I'm opened to any suggestions in regards to this kind of issue.
